"""
Application Common - 공통 유틸리티 및 Base 클래스
"""

from src.application.common.decorators import (
    cache,
    log_execution,
    retry,
    transaction,
    validate_input,
)
from src.application.common.dependencies import (
    DatabaseSession,
    KISAuthDep,
    KISClientDep,
    KISWebSocketDep,
    OrderRepositoryDep,
    RedisDep,
    SettingsDep,
)
from src.application.common.dto import (
    BaseDTO,
    CountDTO,
    ErrorDetailDTO,
    IdResponseDTO,
    IdsResponseDTO,
    MessageDTO,
    PaginatedResponseDTO,
    PaginationDTO,
    ResponseDTO,
    StatusDTO,
    TimestampDTO,
)
from src.application.common.exceptions import (
    ApplicationError,
    AuthenticationError,
    AuthorizationError,
    BusinessLogicError,
    CacheError,
    ConfigurationError,
    DatabaseError,
    EnvironmentError,
    ExternalServiceError,
    InsufficientBalanceError,
    InvalidInputError,
    InvalidTokenError,
    KISAPIServiceError,
    MissingFieldError,
    OrderError,
    PositionNotFoundError,
    RateLimitExceededError,
    ResourceAlreadyExistsError,
    ResourceConflictError,
    ResourceNotFoundError,
    StrategyExecutionError,
    TimeoutError,
    TokenExpiredError,
    ValidationError,
)

__all__ = [
    # Decorators
    "transaction",
    "retry",
    "cache",
    "log_execution",
    "validate_input",
    # Dependencies
    "DatabaseSession",
    "OrderRepositoryDep",
    "KISAuthDep",
    "KISClientDep",
    "KISWebSocketDep",
    "RedisDep",
    "SettingsDep",
    # DTOs
    "BaseDTO",
    "ResponseDTO",
    "PaginationDTO",
    "PaginatedResponseDTO",
    "TimestampDTO",
    "IdResponseDTO",
    "IdsResponseDTO",
    "MessageDTO",
    "CountDTO",
    "StatusDTO",
    "ErrorDetailDTO",
    # Exceptions
    "ApplicationError",
    "ValidationError",
    "InvalidInputError",
    "MissingFieldError",
    "ResourceNotFoundError",
    "ResourceAlreadyExistsError",
    "ResourceConflictError",
    "AuthenticationError",
    "AuthorizationError",
    "TokenExpiredError",
    "InvalidTokenError",
    "BusinessLogicError",
    "OrderError",
    "InsufficientBalanceError",
    "PositionNotFoundError",
    "StrategyExecutionError",
    "ExternalServiceError",
    "KISAPIServiceError",
    "DatabaseError",
    "CacheError",
    "RateLimitExceededError",
    "TimeoutError",
    "ConfigurationError",
    "EnvironmentError",
]
