"""Initial migration: Create tables

Revision ID: 784e41ff1288
Revises: 
Create Date: 2025-10-22 21:51:30.373784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784e41ff1288'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_no', sa.String(length=20), nullable=False, comment='계좌번호'),
    sa.Column('account_name', sa.String(length=100), nullable=True, comment='계좌명'),
    sa.Column('product_code', sa.String(length=10), nullable=False, comment='상품코드 (01: 종합, 03: 선물옵션)'),
    sa.Column('total_balance', sa.Numeric(precision=18, scale=2), nullable=False, comment='총 평가 금액'),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=2), nullable=False, comment='예수금 (현금)'),
    sa.Column('stock_balance', sa.Numeric(precision=18, scale=2), nullable=False, comment='주식 평가 금액'),
    sa.Column('available_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='출금 가능 금액'),
    sa.Column('total_profit_loss', sa.Numeric(precision=18, scale=2), nullable=False, comment='총 손익'),
    sa.Column('total_profit_loss_rate', sa.Numeric(precision=10, scale=4), nullable=False, comment='총 손익률 (%)'),
    sa.Column('realized_profit_loss', sa.Numeric(precision=18, scale=2), nullable=False, comment='실현 손익'),
    sa.Column('unrealized_profit_loss', sa.Numeric(precision=18, scale=2), nullable=False, comment='평가 손익'),
    sa.Column('total_purchase_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='총 매입 금액'),
    sa.Column('total_commission', sa.Numeric(precision=18, scale=2), nullable=False, comment='총 수수료'),
    sa.Column('total_tax', sa.Numeric(precision=18, scale=2), nullable=False, comment='총 세금'),
    sa.Column('position_count', sa.BigInteger(), nullable=False, comment='보유 종목 수'),
    sa.Column('is_paper_trading', sa.Boolean(), nullable=False, comment='모의투자 여부'),
    sa.Column('metadata_json', sa.String(length=1000), nullable=True, comment='추가 메타데이터 (JSON)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_no'), 'accounts', ['account_no'], unique=True)
    op.create_index('ix_accounts_is_paper_trading', 'accounts', ['is_paper_trading'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False, comment='주문 ID (KIS API)'),
    sa.Column('account_no', sa.String(length=20), nullable=False, comment='계좌번호'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='종목코드'),
    sa.Column('symbol_name', sa.String(length=100), nullable=True, comment='종목명'),
    sa.Column('order_type', sa.String(length=10), nullable=False, comment='주문 유형 (buy/sell)'),
    sa.Column('price_type', sa.String(length=10), nullable=False, comment='가격 유형 (market/limit/stop)'),
    sa.Column('order_price', sa.Numeric(precision=18, scale=2), nullable=False, comment='주문 가격'),
    sa.Column('order_quantity', sa.BigInteger(), nullable=False, comment='주문 수량'),
    sa.Column('filled_quantity', sa.BigInteger(), nullable=False, comment='체결 수량'),
    sa.Column('filled_avg_price', sa.Numeric(precision=18, scale=2), nullable=False, comment='체결 평균가'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='주문 상태'),
    sa.Column('status_message', sa.String(length=200), nullable=True, comment='상태 메시지'),
    sa.Column('order_time', sa.DateTime(timezone=True), nullable=False, comment='주문 시각'),
    sa.Column('filled_time', sa.DateTime(timezone=True), nullable=True, comment='체결 시각'),
    sa.Column('commission', sa.Numeric(precision=18, scale=2), nullable=False, comment='수수료'),
    sa.Column('tax', sa.Numeric(precision=18, scale=2), nullable=False, comment='세금'),
    sa.Column('strategy_id', sa.BigInteger(), nullable=True, comment='전략 ID (연동)'),
    sa.Column('metadata_json', sa.String(length=1000), nullable=True, comment='추가 메타데이터 (JSON)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_account_no'), 'orders', ['account_no'], unique=False)
    op.create_index('ix_orders_account_status', 'orders', ['account_no', 'status'], unique=False)
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=True)
    op.create_index('ix_orders_order_time', 'orders', ['order_time'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_strategy_id'), 'orders', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_index('ix_orders_symbol_status', 'orders', ['symbol', 'status'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_no', sa.String(length=20), nullable=False, comment='계좌번호'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='종목코드'),
    sa.Column('symbol_name', sa.String(length=100), nullable=True, comment='종목명'),
    sa.Column('quantity', sa.BigInteger(), nullable=False, comment='보유 수량'),
    sa.Column('available_quantity', sa.BigInteger(), nullable=False, comment='매도 가능 수량'),
    sa.Column('avg_purchase_price', sa.Numeric(precision=18, scale=2), nullable=False, comment='평균 매입가'),
    sa.Column('current_price', sa.Numeric(precision=18, scale=2), nullable=False, comment='현재가'),
    sa.Column('purchase_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='매입 금액'),
    sa.Column('evaluated_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='평가 금액'),
    sa.Column('profit_loss', sa.Numeric(precision=18, scale=2), nullable=False, comment='평가 손익'),
    sa.Column('profit_loss_rate', sa.Numeric(precision=10, scale=4), nullable=False, comment='평가 손익률 (%)'),
    sa.Column('metadata_json', sa.String(length=1000), nullable=True, comment='추가 메타데이터 (JSON)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_positions_account_no', 'positions', ['account_no'], unique=False)
    op.create_index('ix_positions_account_symbol', 'positions', ['account_no', 'symbol'], unique=True)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='전략명'),
    sa.Column('description', sa.Text(), nullable=True, comment='전략 설명'),
    sa.Column('strategy_type', sa.String(length=50), nullable=False, comment='전략 유형'),
    sa.Column('account_no', sa.String(length=20), nullable=False, comment='계좌번호'),
    sa.Column('symbols', sa.String(length=500), nullable=False, comment='대상 종목 (쉼표 구분)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='전략 상태'),
    sa.Column('config_json', sa.Text(), nullable=False, comment='전략 설정 (JSON)'),
    sa.Column('total_executions', sa.BigInteger(), nullable=False, comment='총 실행 횟수'),
    sa.Column('successful_executions', sa.BigInteger(), nullable=False, comment='성공 실행 횟수'),
    sa.Column('failed_executions', sa.BigInteger(), nullable=False, comment='실패 실행 횟수'),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 실행 시각'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='시작 시각'),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True, comment='중지 시각'),
    sa.Column('metadata_json', sa.String(length=1000), nullable=True, comment='추가 메타데이터 (JSON)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_account_no'), 'strategies', ['account_no'], unique=False)
    op.create_index('ix_strategies_account_status', 'strategies', ['account_no', 'status'], unique=False)
    op.create_index(op.f('ix_strategies_name'), 'strategies', ['name'], unique=False)
    op.create_index('ix_strategies_status', 'strategies', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_strategies_status', table_name='strategies')
    op.drop_index(op.f('ix_strategies_name'), table_name='strategies')
    op.drop_index('ix_strategies_account_status', table_name='strategies')
    op.drop_index(op.f('ix_strategies_account_no'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index('ix_positions_account_symbol', table_name='positions')
    op.drop_index('ix_positions_account_no', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_orders_symbol_status', table_name='orders')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_strategy_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index('ix_orders_order_time', table_name='orders')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_index('ix_orders_account_status', table_name='orders')
    op.drop_index(op.f('ix_orders_account_no'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_accounts_is_paper_trading', table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_no'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
