"""Add trailing stop fields to strategy_symbol_states

Revision ID: 9c1f1cc170b7
Revises: 20260108_analysis_history
Create Date: 2026-01-13 05:55:34.972189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1f1cc170b7'
down_revision: Union[str, Sequence[str], None] = '20260108_analysis_history'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_history', 'gc_state',
               existing_type=sa.VARCHAR(length=30),
               comment='골든크로스 상태 (NOT_GC, GC_ACTIVE, WAITING_FOR_PULLBACK, READY_TO_BUY)',
               existing_comment='골든크로스 상태',
               existing_nullable=True)
    op.alter_column('analysis_history', 'is_death_cross',
               existing_type=sa.BOOLEAN(),
               comment='데드크로스 여부 (MA55 < MA160)',
               existing_comment='데드크로스 여부',
               existing_nullable=True)
    op.alter_column('analysis_history', 'sell_recommendation',
               existing_type=sa.VARCHAR(length=20),
               comment='매도 추천 (HOLD, WATCH, WEAK_SELL, CONSIDER_SELL, SELL, STRONG_SELL)',
               existing_comment='매도 추천',
               existing_nullable=True)
    op.create_index(op.f('ix_analysis_history_analysis_type'), 'analysis_history', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_analysis_history_symbol'), 'analysis_history', ['symbol'], unique=False)
    op.drop_constraint(op.f('uq_stock_universe_symbol'), 'stock_universe', type_='unique')
    op.create_index(op.f('ix_stock_universe_avg_volume_20d'), 'stock_universe', ['avg_volume_20d'], unique=False)
    op.create_index(op.f('ix_stock_universe_sector'), 'stock_universe', ['sector'], unique=False)
    op.create_index(op.f('ix_strategy_signals_signal_status'), 'strategy_signals', ['signal_status'], unique=False)
    op.add_column('strategy_symbol_states', sa.Column('highest_price', sa.Numeric(precision=15, scale=2), nullable=True, comment='포지션 진입 후 최고가'))
    op.add_column('strategy_symbol_states', sa.Column('trailing_stop_activated', sa.Boolean(), nullable=False, comment='트레일링 스탑 활성화 여부'))
    op.add_column('strategy_symbol_states', sa.Column('trailing_stop_activated_at', sa.DateTime(timezone=True), nullable=True, comment='트레일링 스탑 활성화 시점'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_symbol_states', 'trailing_stop_activated_at')
    op.drop_column('strategy_symbol_states', 'trailing_stop_activated')
    op.drop_column('strategy_symbol_states', 'highest_price')
    op.drop_index(op.f('ix_strategy_signals_signal_status'), table_name='strategy_signals')
    op.drop_index(op.f('ix_stock_universe_sector'), table_name='stock_universe')
    op.drop_index(op.f('ix_stock_universe_avg_volume_20d'), table_name='stock_universe')
    op.create_unique_constraint(op.f('uq_stock_universe_symbol'), 'stock_universe', ['symbol'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_analysis_history_symbol'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_analysis_type'), table_name='analysis_history')
    op.alter_column('analysis_history', 'sell_recommendation',
               existing_type=sa.VARCHAR(length=20),
               comment='매도 추천',
               existing_comment='매도 추천 (HOLD, WATCH, WEAK_SELL, CONSIDER_SELL, SELL, STRONG_SELL)',
               existing_nullable=True)
    op.alter_column('analysis_history', 'is_death_cross',
               existing_type=sa.BOOLEAN(),
               comment='데드크로스 여부',
               existing_comment='데드크로스 여부 (MA55 < MA160)',
               existing_nullable=True)
    op.alter_column('analysis_history', 'gc_state',
               existing_type=sa.VARCHAR(length=30),
               comment='골든크로스 상태',
               existing_comment='골든크로스 상태 (NOT_GC, GC_ACTIVE, WAITING_FOR_PULLBACK, READY_TO_BUY)',
               existing_nullable=True)
    # ### end Alembic commands ###
